# Generated by Django 5.2.17 on 2026-09-30 10:40

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text="Customer's proof of payment (private)", storage=shop.models.private_storage, upload_to='pop/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction reference', max_length=100),
        ),
    ]
