# Generated by Django 5.2.17 on 2026-09-30 10:52

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_proof_of_payment_alter_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text="Customer's proof of payment (private)", storage=shop.models.private_storage, upload_to=shop.models.pop_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Digital products only. Stored privately on Backblaze B2.', storage=shop.models.private_storage, upload_to=shop.models.digital_path),
        ),
    ]
