# Generated by Django 5.2.17 on 2026-10-01 08:04

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Tailor, Jerseys producer', max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(help_text='e.g. Chairperson, Secretary, Treasurer', max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to=shop.models.executive_photo_path)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
